# Generated by Django 5.2.1 on 2025-05-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_email_cliente_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('janeiro', models.FloatField(default=0)),
                ('fevereiro', models.FloatField(default=0)),
                ('marco', models.FloatField(default=0)),
                ('abril', models.FloatField(default=0)),
                ('maio', models.FloatField(default=0)),
                ('junho', models.FloatField(default=0)),
                ('julho', models.FloatField(default=0)),
                ('agosto', models.FloatField(default=0)),
                ('setembro', models.FloatField(default=0)),
                ('outubro', models.FloatField(default=0)),
                ('novembro', models.FloatField(default=0)),
                ('dezembro', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
