# Generated by Django 5.2.1 on 2025-05-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_email_cliente_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limpeza', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('tempo', models.TimeField()),
                ('dificuldade', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpezas', to='clientes.cliente')),
            ],
        ),
    ]
