# Generated by Django 5.2.1 on 2025-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.IntegerField()),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
    ]
