# Generated by Django 5.2.1 on 2025-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('irra_jan', models.FloatField()),
                ('irra_fev', models.FloatField()),
                ('irra_mar', models.FloatField()),
                ('irra_abr', models.FloatField()),
                ('irra_mai', models.FloatField()),
                ('irra_jun', models.FloatField()),
                ('irra_jul', models.FloatField()),
                ('irra_ago', models.FloatField()),
                ('irra_set', models.FloatField()),
                ('irra_out', models.FloatField()),
                ('irra_nov', models.FloatField()),
                ('irra_dez', models.FloatField()),
            ],
        ),
    ]
