# Generated by Django 5.2.1 on 2025-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('potencia_maxima', models.FloatField()),
                ('fases', models.IntegerField(choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')])),
            ],
        ),
    ]
